routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PostController@index');
Route::get('/category/{post}', 'CategoryController@index');

Route::get('/master', function () {
    return view('template.master');
});

Route::post('/posts/{post}', 'CommentController@store');

Route::resource('posts','PostController');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

resources/views/pages/admin.blade.php
@extends('template.master')

@section('title')
<title>Postingan Saya | LaraBlog</title>
@endsection

@section('content')
<div class="mt-3 ml-3 mr-3">
<div class="card">
              <div class="card-header">
                <h3 class="card-title">Postingan Saya</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                @if(session('success'))
                  <div class="alert alert-success">
                    {{ session('success') }}
                  </div>
                @endif
                <a class="btn btn-primary" href="{{route('posts.create')}}">Buat Postingan Baru</a>
                <table class="table table-bordered">
                  <thead>                  
                    <tr>
                      <th>Judul</th>
                      <th style="width: 40px">Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    @forelse($posts->reverse() as $key => $post)
                    <tr>
                      <td><a href="{{route('posts.show', ['post' => $post->id])}}">{{ $post->title }}</a></td>
                      @if($post->user_id == Auth::id())
                      <td style="display: flex;">
                        <a href="{{route('posts.edit', ['post' => $post->id])}}" class="btn btn-default btn-sm ml-1 mr-1">edit</a>
                        <form action="{{route('posts.destroy', ['post' => $post->id])}}" method="POST">
                          @csrf
                          @method('DELETE')
                          <input type="submit" value="delete" class="btn btn-danger btn-sm ml-1 mr-1">
                        </form>
                      </td>
                      @endif
                      @if($post->user_id != Auth::id())
                      <td></td>
                      @endif
                    </tr>
                    @empty
                    <tr>
                      <td colspan="4" align="center">Tidak ada pertanyaan</td>
                    </tr>
                    @endforelse
                  </tbody>
                </table>
              </div>
</div>  
</div>
@endsection

resources/views/pages/category_index.blade.php
@extends('template.master')

@section('title')
<title>Kategori {{ $category->name }} | LaraBlog</title>
@endsection

@section('content')
    @forelse($category->post->reverse() as $post)
      <div class="mt-3 ml-3 mr-3">
          <div class="card">
              <div class="card-header">
                <h3><a href="{{route('posts.show', ['post' => $post->id])}}" style="color: black;">{{$post->title}}</a></h3>
              </div>
              <div class="card-body">
                <div class="text-muted">
                    <p>
                    <small>Diposting pada: {{$post->created_at}}&nbsp;&nbsp;</small>
                    <small>Diubah pada: {{$post->updated_at}}&nbsp;&nbsp;</small>
                    <small>Oleh: {{$post->user->name}}  </small>
                    </p>
                </div>
                <p>
                  {!! $limit_str->limit($post->body, $limit = 1000, $end = '...') !!}
                  @if (strlen($post->body) > 1000)
                  <a href="{{route('posts.show', ['post' => $post->id])}}">Baca Selengkapnya</a>
                  @endif
                </p>
                <p>
                  Kategori:&nbsp;
                  @forelse($post->category as $percategory)
                    <a href="/category/{{{$percategory->id}}}" class="btn btn-sm btn-success">{{$percategory->name}}</a>
                    @empty
                    Tidak ada kategori
                  @endforelse
                </p>
              </div>
          </div>
      </div>
      @empty
      <div></div>
      <div class="mt-3 ml-3 mr-3">
        <div class="card">
          <div class="mb-3"></div>
          <p align="center"><b>Tidak ada post</b></p>
        </div>
      </div>
    @endforelse
@endsection

resources/views/pages/create.blade.php
@extends('template.master')

@section('title')
<title>Buat Postingan Baru | LaraBlog</title>
@endsection

@push('script_head')
<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
@endpush

@section('content')
<div class="mt-3 ml-3 mr-3">
<div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Buat Postingan Baru</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" action="{{route('posts.store')}}" method="POST">
                @csrf
                <div class="card-body">
                  <div class="form-group">
                    <label for="title">Judul Postingan</label>
                    <input type="text" class="form-control" id="title" value="{{ old('title','') }}" name="title" placeholder="Masukkan Judul">
                    @error('title')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                  <div class="form-group">
                    <label for="body">Isi Postingan</label>
                    <textarea name="body" class="form-control my-editor">{!! old('body', '') !!}</textarea>
                    @error('body')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                  </div>
                  <div class="form-group">
                    <label for="categories">Kategori</label>
                    <input type="text" class="form-control" id="categories" value="{{ old('categories','') }}" name="categories" placeholder="Pisahkan dengan koma, contoh: Framework Laravel,Framework NodeJS,Bahasa Pemrograman">
                    @error('categories')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                  </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Buat</button>
                </div>
              </form>
            </div>
</div>
@endsection

@push('script')
<script>
  var editor_config = {
    path_absolute : "/",
    selector: "textarea.my-editor",
    plugins: [
      "advlist autolink lists link image charmap print preview hr anchor pagebreak",
      "searchreplace wordcount visualblocks visualchars code fullscreen",
      "insertdatetime media nonbreaking save table contextmenu directionality",
      "emoticons template paste textcolor colorpicker textpattern"
    ],
    toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media",
    relative_urls: false,
    file_browser_callback : function(field_name, url, type, win) {
      var x = window.innerWidth || document.documentElement.clientWidth || document.getElementsByTagName('body')[0].clientWidth;
      var y = window.innerHeight|| document.documentElement.clientHeight|| document.getElementsByTagName('body')[0].clientHeight;

      var cmsURL = editor_config.path_absolute + 'laravel-filemanager?field_name=' + field_name;
      if (type == 'image') {
        cmsURL = cmsURL + "&type=Images";
      } else {
        cmsURL = cmsURL + "&type=Files";
      }

      tinyMCE.activeEditor.windowManager.open({
        file : cmsURL,
        title : 'Filemanager',
        width : x * 0.8,
        height : y * 0.8,
        resizable : "yes",
        close_previous : "no"
      });
    }
  };

  tinymce.init(editor_config);
</script>
@endpush

resources/views/pages/edit.blade.php
@extends('template.master')

@section('title')
<title>Edit | LaraBlog</title>
@endsection

@push('script_head')
<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
@endpush

@section('content')
<div class="mt-3 ml-3 mr-3">
<div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Edit Postingan</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" action="{{route('posts.update', ['post' => $posts->id])}}" method="POST">
                @csrf
                @method('PUT')
                <div class="card-body">
                  <div class="form-group">
                    <label for="title">Judul Postingan</label>
                    <input type="text" class="form-control" id="title" value="{{ old('title',$posts->title) }}" name="title" placeholder="Masukkan Judul">
                    @error('title')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                  <div class="form-group">
                    <label for="body">Isi Postingan</label>
                    <textarea name="body" class="form-control my-editor">{!! old('body', $posts->body) !!}</textarea>
                    @error('body')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                  </div>
                  <div class="form-group">
                    <label for="categories">Kategori</label>
                    <input type="text" class="form-control" id="categories" value="{{ old('categories', $posts->category) }}" name="categories" placeholder="Pisahkan dengan koma, contoh: Framework Laravel,Framework NodeJS,Bahasa Pemrograman">
                    @error('categories')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                  </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Update</button>
                </div>
              </form>
            </div>
</div>
@endsection

@push('script')
<script>
  var editor_config = {
    path_absolute : "/",
    selector: "textarea.my-editor",
    plugins: [
      "advlist autolink lists link image charmap print preview hr anchor pagebreak",
      "searchreplace wordcount visualblocks visualchars code fullscreen",
      "insertdatetime media nonbreaking save table contextmenu directionality",
      "emoticons template paste textcolor colorpicker textpattern"
    ],
    toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media",
    relative_urls: false,
    file_browser_callback : function(field_name, url, type, win) {
      var x = window.innerWidth || document.documentElement.clientWidth || document.getElementsByTagName('body')[0].clientWidth;
      var y = window.innerHeight|| document.documentElement.clientHeight|| document.getElementsByTagName('body')[0].clientHeight;

      var cmsURL = editor_config.path_absolute + 'laravel-filemanager?field_name=' + field_name;
      if (type == 'image') {
        cmsURL = cmsURL + "&type=Images";
      } else {
        cmsURL = cmsURL + "&type=Files";
      }

      tinyMCE.activeEditor.windowManager.open({
        file : cmsURL,
        title : 'Filemanager',
        width : x * 0.8,
        height : y * 0.8,
        resizable : "yes",
        close_previous : "no"
      });
    }
  };

  tinymce.init(editor_config);
</script>
@endpush

resources/views/pages/index.blade.php
@extends('template.master')

@section('title')
<title>LaraBlog</title>
@endsection

@section('content')
    @foreach($posts->reverse() as $key => $post)
      <div class="mt-3 ml-3 mr-3">
          <div class="card">
              <div class="card-header">
                <h3><a href="{{route('posts.show', ['post' => $post->id])}}" style="color: black;">{{$post->title}}</a></h3>
              </div>
              <div class="card-body">
                <div class="text-muted">
                    <p>
                    <small>Diposting pada: {{$post->created_at}}&nbsp;&nbsp;</small>
                    <small>Diubah pada: {{$post->updated_at}}&nbsp;&nbsp;</small>
                    <small>Oleh: {{$post->user->name}}  </small>
                    </p>
                </div>
                <p>
                  {!! $limit_str->limit($post->body, $limit = 1000, $end = '...') !!}
                  @if (strlen($post->body) > 1000)
                  <a href="{{route('posts.show', ['post' => $post->id])}}">Baca Selengkapnya</a>
                  @endif
                </p>
                <p>
                  Kategori:&nbsp;
                  @forelse($post->category as $percategory)
                    <a href="/category/{{{$percategory->id}}}" class="btn btn-sm btn-success">{{$percategory->name}}</a>
                    @empty
                    Tidak ada kategori
                  @endforelse
                </p>
              </div>
          </div>
      </div>
    @endforeach
@endsection

resources/views/pages/show.blade.php
@extends('template.master')

@section('title')
<title>{{$posts->title}} | LaraBlog</title>
@endsection

@section('content')
<div class="mt-3 ml-3 mr-3">
    <div class="card card-widget">
        <div class="card-header">
        <div class="user-block">
            <p class="h3">{{$posts->title}}</p>
        </div>
        @guest
            @if (Route::has('register'))
            @endif
            @else
                @if(Auth::user()->id == $posts->user->id)
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" title="Edit">
                    <a href="{{route('posts.edit', ['post' => $posts->id])}}"><i class="fas fa-edit"></i></a>
                    </button>
                </div>
                @endif
        @endguest
        </div>
        
        <div class="card-body">
            <span class="float-right text-muted" style="display: block;">
                <div class="callout callout-info">
                <div class="row">
                    <p><small>Diposting pada: {{$posts->created_at}}</small></p>
                </div>
                <div class="row">
                    <p><small>Diubah pada: {{$posts->updated_at}}</small></p>
                </div>
                <div class="row">
                    <p><small>Oleh: {{$posts->user->name}}</small></p>
                </div>
                </div>
            </span>
            <p>
            {!! $posts->body !!}
            </p>
            <p>
              Kategori:&nbsp;
              @forelse($posts->category as $percategory)
                <a href="/category/{{{$percategory->id}}}" class="btn btn-sm btn-success">{{$percategory->name}}</a>
                @empty
                Tidak ada kategori
              @endforelse
            </p>
        </div>
    <!--<h4>{{$posts->title}}</h4>
    <p>Penanya: {{$posts->user->name}}</p>
    <p>{{$posts->body}}</p>
    <p>Tags:
        @forelse($posts->category as $perkategori)
            <button class="btn btn-primary btn-sm"> {{$perkategori->name}} </button>
            @empty
            No tags
        @endforelse
    </p>-->
    </div>
</div>
@endsection

@section('comment')
<div class="card-footer card-comments">
      <div class="post">
        <strong class="mb-3">Comment ({{$posts->comment->count()}})</strong>
      </div>
      @foreach($posts->comment->reverse() as $percomment)
        <div class="card-comment">
          <span class="username">
            {{ $percomment->user->name }}
          <span class="text-muted float-right">{{ $percomment->created_at }}</span>
          </span>
            {{ $percomment->body }}
        </div>
      @endforeach
    </div>
@guest
    @if (Route::has('register'))
    <p align="center">Login terlebih dahulu agar bisa berkomentar</p>
    @endif
    @else
    <div class="card-footer">
      <form action="/posts/{post}" method="post">
        @csrf
        <input type="hidden" name="post_id" value="{{$posts->id}}">

        <div class="img-push row">
          <div class="input-group">
            <input type="text" class="disabled form-control" name="comment" placeholder="Tambahkan komentar">
            <button type="submit" class="btn btn-info ml-2" style="border-radius:50%">
              <i class="fa fa-location-arrow"></i>
            </button>
          </div>
        </div>
      </form>
    </div>
@endguest
@endsection